// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DisableAntispy() {
  return window['go']['app']['App']['DisableAntispy']();
}

export function EnableAntispy() {
  return window['go']['app']['App']['EnableAntispy']();
}

export function GetEvents() {
  return window['go']['app']['App']['GetEvents']();
}

export function IsAntispyActive() {
  return window['go']['app']['App']['IsAntispyActive']();
}

export function Quit() {
  return window['go']['app']['App']['Quit']();
}

export function Show() {
  return window['go']['app']['App']['Show']();
}
