// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function DisableAntispy():Promise<void>;

export function EnableAntispy():Promise<void>;

export function GetEvents():Promise<Array<app.Event>>;

export function IsAntispyActive():Promise<boolean>;

export function Quit():Promise<void>;

export function Show():Promise<void>;
